### DISCUSSION TITLE
How can I change size of  dropdown arrow and loader spinner?

### DISCUSSION THREAD

**Discussion by scramatte** [sagalbot/vue-select#1800] [Help Wanted]
Hi,

How can I change size of dropdown arrow and loader spinner?
I've tried to set following variables

```css
--vs-controls-size: 0.75;
--vs-controls--spinner-size: 0.75;
```

If I override styles  vs__spinner , I've been able to reduce size of the spinner but I loose animation:

```css
.vs__spinner {
          transform: scale(var(--vs-controls-size)) !important
}
```
Note that without word "!important" the style is not applied.

I'm unable to get it working properly
Can you give me an hand?

Regards
