### ISSUE TITLE
transition is not working in dropdown-menu

### ISSUE THREAD

**Issue by Tanchiky** [sagalbot/vue-select#1208]
I listed Transition css for the dropdown, but it doesn't work at all It was. 
How can I use Transition?

- Setting the following to css does not work at all (for e.g.)
```css
.vs__fade-enter-active, .vs__fade-leave-active {
  transition: opacity .5s;
}
.vs__fade-enter, .vs__fade-leave-to {
  opacity: 0;
}
```

[NITS]
It seems to be due to the fact that the key is not set in the ul tag. Could you please check this?
(That's the VS__dropdown-menu in the Select.vue)

thanks :D
