### ISSUE TITLE
Disabled options should display a not-allowed cursor.

### ISSUE THREAD

**Issue by thomasdziedzic-census** [sagalbot/vue-select#1449]
**Is your feature request related to a problem? Please describe.**
This is related to a visual style opinion. The default cursor for disabled options is inherited: https://github.com/sagalbot/vue-select/blob/v3.4.0/src/scss/modules/_dropdown-option.scss#L25

This ends up being the text selection cursor on my machine, which looks weird when the option is disabled.

**Describe the solution you'd like**
I currently use this style:

```scss
.vs__dropdown-option--disabled {
  &:hover {
    cursor: not-allowed !important;
  }
}
```

**Describe alternatives you've considered**
Maybe parameterize the cursor so that it can be changed with a variable?
