### ISSUE TITLE
No way to set "class" attribute  to option element

### ISSUE THREAD

**Issue by rx-837** [sagalbot/vue-select#1542]
**Is your feature request related to a problem? Please describe.**
Drowdown element has a structure `ul>li>slot`.

I have a case when should to set custom class name to option element(li).

To resolve it i use "option" slot

```vue
<template>
  <v-select class="custom-select">
    <template #option="option">
      <div class="custom-select__option">
      </div>
    </template>
  </v-select>
</template>
```

```scss
.custom-select {
  .vs__dropdown-option {
    padding: 0;
  }
  &__option {
    padding: 3px 20px; // like vs__dropdown-option before
  }
}
```

This way is have disadvantages like css overriding of ".vs__dropdown-option"

**Describe the solution you'd like**
Proposal is simple - add to component props like `:li-class-name="custom-class"`(option-class-name), `:ul-class-name="custom-class"`(menu-class-name)

**Describe alternatives you've considered**
Another way is create component Option like OpenIndicator. Also possible wrap li element to slot.

**Additional context**
-
