### ISSUE TITLE
I'm not able to change vs--disabled background styles

### ISSUE THREAD

**Issue by FabianGML** [sagalbot/vue-select#1831]
> Please respect maintainers time by filling in these sections. Your issue will likely be closed without this information.

- Vue Version: 3.4.19
- Vue Select Version: 4.0.0-beta.6

**Describe the bug**
When I add a disabled attribute to the v-select component, adds a new class named: 'vs--disabled'.
I've been able to change the border and other styles, but i have a problem with the background, I saw in the docs that i can override the global variable --vs-state-disabled-bg, but this doesn't work as well

**Steps To Reproduce**
Just add a disable attribute and try to change the background color

**Expected behavior**
Handle the background color as my system needs

**Screenshots**
<img width="314" alt="Captura de pantalla 2024-04-23 a la(s) 3 47 27 p m" src="https://github.com/sagalbot/vue-select/assets/93468546/36a5cca8-f1b4-47d5-83a3-e20057360006">

**Comment by hbiblia** [comment]
``` css
.vs--disabled .vs__dropdown-toggle,
.vs--disabled .vs__clear,
.vs--disabled .vs__search,
.vs--disabled .vs__selected,
.vs--disabled .vs__open-indicator {
    background: red;
}
```
