### ISSUE TITLE
Placeholder missing when not searchable

### ISSUE THREAD

**Issue by bformet** [sagalbot/vue-select#222]
I just found out that the `placeholder` is not displayed when `v-select` has `:searchable="false"`

**Comment by ama-gi** [comment]
I had the same problem.
Its because the input field with the placeholder is set to max-width: 1px when searchable is false.

Heres a simple temporary fix:

```CSS
.v-select.unsearchable input[type="search"] {
    max-width: none;
}
.v-select.unsearchable > .dropdown-toggle > .selected-tag + input[type="search"] {
    max-width: 1px;
}
```
