### ISSUE TITLE
How can we theme the vSelect

### ISSUE THREAD

**Issue by nacr-dev** [sagalbot/vue-select#30]
Is there any support for themes?

And if so how can it be done?

tks

**Comment by sagalbot** [comment]
There aren't any pre-made themes at the moment. We discussed it in PR #16 but decided that it was unlikely the themes we produce are going to line up with a given users design. If I was wrong about that, I'm happy to merge #16. At the moment, your best bet would be write your own styles from an external stylesheet. 

What are you looking for in terms of themes?

**Comment by sagalbot** [comment]
For example, on the demo site, I've just added an ID to the element and add some simple styles to change the colors a bit:

```css
/* Cyan theme */
#v-select .selected-tag {
    color: #147688;
    background-color: #d7f3f9;
    border-color: #91ddec;
}

#v-select.dropdown.open .dropdown-toggle,
#v-select.dropdown.open .dropdown-menu {
    border-color: #4CC3D9;
}

#v-select .active a {
    background: rgba(50,50,50,.1);
    color: #333;
}

#v-select.dropdown .highlight a,
#v-select.dropdown li:hover a {
    background: #4CC3D9;
    color: #fff;
}
```
