### ISSUE TITLE
Clear selection button appears as two strange characters

### ISSUE THREAD

**Issue by nathan815** [sagalbot/vue-select#507]
I'm building a Chrome extension with Vue.js and am having a fairly strange issue with vue-select. The clear selection shows up as "Ã—" instead of an "x" icon like normal. This suddenly started after I set up webpack and began using single file `.vue` components.

<img width="410" alt="screen shot 2018-04-10 at 12 15 31 am" src="https://user-images.githubusercontent.com/1972782/38536053-0054ed7e-3c55-11e8-9c72-64efbc4c78da.png">

These characters are actually showing up in the Chrome dev tools DOM Inspector so it appears that Vue is rendering the element with these characters. (Also, I have the page's charset set to UTF-8.)

Any ideas what could be causing this?

**Comment by sagalbot** [comment]
It could be a font-family issue? The open indicator uses the following markup and styles:

```html
<i v-if="!noDrop" ref="openIndicator" role="presentation" class="open-indicator"></i>
```

```css
/* Open Indicator */
  .v-select .open-indicator {
    position: absolute;
    bottom: 6px;
    right: 10px;
    display: inline-block;
    cursor: pointer;
    pointer-events: all;
    transition: all 150ms cubic-bezier(1.000, -0.115, 0.975, 0.855);
    transition-timing-function: cubic-bezier(1.000, -0.115, 0.975, 0.855);
    opacity: 1;
    height: 20px; width: 10px;
  }
  .v-select .open-indicator:before {
    border-color: rgba(60, 60, 60, .5);
    border-style: solid;
    border-width: 3px 3px 0 0;
    content: '';
    display: inline-block;
    height: 10px;
    width: 10px;
    vertical-align: top;
    transform: rotate(133deg);
    transition: all 150ms cubic-bezier(1.000, -0.115, 0.975, 0.855);
    transition-timing-function: cubic-bezier(1.000, -0.115, 0.975, 0.855);
    box-sizing: inherit;
  }
  /* Open Indicator States */
  .v-select.open .open-indicator:before {
    transform: rotate(315deg);
  }
```
