### ISSUE TITLE
Z-index problems

### ISSUE THREAD

**Issue by crashkonijn** [sagalbot/vue-select#566]
Hello,

While implementing this into our project I ran into the following issue where the popup box of vue-select will render below other items on the page. I've tried making the z-index higher but this doesn't change anything. I've tried looking for similar issues here but I was unable to find an answer, hopefully you guys can help me out!

We're using bootstrap 4.1.1 and vue-select 2.4.0.

![screenshot from 2018-06-14 09-42-14](https://user-images.githubusercontent.com/5364802/41399009-74a70a58-6fb9-11e8-9b61-7e5ddebe57a7.png)

**Comment by crashkonijn** [comment]
I've been able to narrow the problem down to a problem caused by animate.css, specifically this css line:

```css
.animated {
  animation-fill-mode: both;
}
```
I've been unable to write css that fixes this by applying animation-fill-mode: none; to any of the vue-select styles, maybe one of you guys can manage this? Animated.css is a very popular package.

In the mean time this is the solution that I'm applying for any animations that are parents of my vue-select instance:

```css
.animated {
    &.fill-fix {
        animation-fill-mode: none;
    }
}
```
