### ISSUE TITLE
CSS Conflict with vue-bootstrap/bootstrap4

### ISSUE THREAD

**Issue by soichih** [sagalbot/vue-select#662]
I am using vue-select to replace vue-bootstrap default select box. I believe this issue started when I upgraded vue-bootstrap to 2.0 (which loads bootstrap 4.1.1), but vue-select stying seems to be broken with the version I am using (v2.5.1)

![screenshot from 2018-09-25 23-25-19](https://user-images.githubusercontent.com/923896/46055700-2f801100-c11b-11e8-801f-3300fcda6589.png)

(See the odd caret mark on the right side of the select box, and the height of the select box seems unnecessarily bloated..)

I am loading bootstrap css like so..

```
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-vue/dist/bootstrap-vue.min.css'
```

If I remove these, the issue goes away.
![screenshot from 2018-09-25 23-34-11](https://user-images.githubusercontent.com/923896/46055772-8980d680-c11b-11e8-87eb-59fd00909882.png)

I am not sure if this is vue-bootstrap issue, but is there anyway to make vue-select not conflict with vue-bootstrap?

**Comment by soichih** [comment]
I've patched this issue with following CSS rules for now

```css
 /*prevent bootstrap-vue css conflict*/
.v-select.dropdown .dropdown-toggle {
content: inherit;
}
.v-select.dropdown .form-control {
height: inherit;
}

```
