### ISSUE TITLE
Values longer than field itself breaks UI

### ISSUE THREAD

**Issue by ipa1981** [sagalbot/vue-select#754]
![image](https://user-images.githubusercontent.com/15179453/52658260-43c67e00-2f03-11e9-937a-833d078c8e7b.png)

https://codepen.io/anon/pen/QYxxOr

**Comment by agm1984** [comment]
This can probably be fixed by applying these styles to that container:

``` css
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

That is also a borderline-unreasonable width for a dropdown with country values in it :)

**Comment by sagalbot** [comment]
Related to #750

**Comment by wmarcos** [comment]
I fixed re-writing flex-wrap for the container

```
.v-select .vs__selected-options {
    flex-wrap: nowrap;
}
```
it works ok for me.

**Comment by theGrower** [comment]
> This can probably be fixed by applying these styles to that container:
> 
> ```css
> overflow: hidden;
> text-overflow: ellipsis;
> white-space: nowrap;
> ```
> 
> That is also a borderline-unreasonable width for a dropdown with country values in it :)

Her is what is rendering in our application: 
![image](https://user-images.githubusercontent.com/11525829/79586806-9ec3aa00-809f-11ea-8360-f951c85433af.png)

When I implement this fix the selected text that overflows looks good, but `overflow: hidden;` prevents the drop down box from rendering outside of the bounds of the container.
![image](https://user-images.githubusercontent.com/11525829/79586922-cb77c180-809f-11ea-97d5-01b425e47d7d.png)

> I fixed re-writing flex-wrap for the container
> 
> ```
> .v-select .vs__selected-options {
>     flex-wrap: nowrap;
> }
> ```
> 
> it works ok for me.

This just breaks up a long value word wrapping every word causing the text to be out of bounds of the box. 
![image](https://user-images.githubusercontent.com/11525829/79586943-d2063900-809f-11ea-922f-a5e8ac73e90b.png)

We've been facing this problem for months, and mostly we've either put up with some of the ugliness of it, or we've adjusted the size of the select box to accommodate. However, this particular use case it would not be appropriate for either of those options. 

I've also tried narrowing down the scss down to the text are tag with the following and still the `overflow: none;` continues to break the drop down box.
```
.ept_v-select-oem, .dropdown-toggle, .vs__selected-options, .selected-tag {
  text-overflow: clip;
  white-space: nowrap;
  flex-wrap: nowrap;
  overflow: none;
}
```

Here is the Vue html with the v-select container. The class on the container div is where I'm applying styles. I've tried applying them to the v-select as well, and using various other scss stylings in attempt to overwrite the v-select css has not garnered sufficient results. 
```
<div class="ept_v-select-oem">
  <label for="oem">{{ getContentItem("OEM") }}:</label>
  <v-select
    id="oem"
    v-model="oem"
    :options="oemListOptions.Items"
    name="oem"          
    :select-on-tab="true"
    class="form-control"
    @search="searchOems"
  />
</div>
```

**Comment by aaronransley** [comment]
I ran into this same issue this evening, and adding the following CSS helped:

```css
.vs__selected-options {
  flex-wrap: nowrap;
  max-width: calc(100% - 25px);
}

.vs__selected {
  display: block;
  white-space: nowrap;
  text-overflow: ellipsis;
  max-width: 100%;
  overflow: hidden;
}
```

**Comment by ipa1981** [comment]
@aaronransley. The fix is pretty decent. But not ideal. There is still the element `.vs__search` making the text narrower than it could be in the field when selected.

![image](https://user-images.githubusercontent.com/15179453/86794453-37e9d780-c075-11ea-91fe-176e0ff85053.png)

**Comment by theGrower** [comment]
> 
> 
> @aaronransley. The fix is pretty decent. But not ideal. There is still the element `.vs__search` making the text narrower than it could be in the field when selected.
> 
> ![image](https://user-images.githubusercontent.com/15179453/86794453-37e9d780-c075-11ea-91fe-176e0ff85053.png)

We shifted to creating our own CSS styles and applying them to vanilla HTML 5 inputs. FWIW.

**Comment by aaronransley** [comment]
> @aaronransley. The fix is pretty decent. But not ideal. There is still the element `.vs__search` making the text narrower than it could be in the field when selected.
> 
> ![image](https://user-images.githubusercontent.com/15179453/86794453-37e9d780-c075-11ea-91fe-176e0ff85053.png)

I noticed this as well, but couldn't figure out a way to target the appropriate combinations of classes to hide the `.vs__search` field when not needed. It seems to be used for the placeholder label, as well as when the dropdown is open, but I didn't dig too deep.

@sagalbot Is there an official recommendation on how to work around these low-width dropdown edge cases?

**Comment by sobrinho** [comment]
Got caught by that today. Any fixes that do work in the latest version?

**Comment by mwickens** [comment]
I’ve tried all the suggestions here and can’t make this work. My content is loading in a sidebar (an Outlook add-in), so the width is small and out of my control. A solution would be much appreciated!

**Comment by sobrinho** [comment]
I managed to have this:

```css
.vs__selected-options {
  flex-wrap: nowrap;
  max-width: calc(100% - 41px);
}

.vs__selected {
  margin-top: 6px;
  display: block;
  white-space: nowrap;
  text-overflow: ellipsis;
  max-width: 100%;
  overflow: hidden;
}

.vs__search {
  position: absolute;
}

.vs--open .vs__search {
  position: static;
}

.vs__dropdown-option {
  white-space: normal;
}
```

**Comment by ipa1981** [comment]
@sobrinho Good enough. However it has some problem with "jumping" element height (look below). It does not dynamically respect "clearance" button like in @aaronransley example also. It would be amazing if @sagalbot would somehow recommend how to perfectly resolve this.

![Peek 2020-07-08 10-22](https://user-images.githubusercontent.com/15179453/86889851-16d0c780-c105-11ea-978f-1effa89f812f.gif)

**Comment by sobrinho** [comment]
Yeah, I only have a single-mode here, so I didn't try to fix it at all.

The best would be a fix in the project, I will try in the next days and open a PR.

**Comment by XNL073** [comment]
Any update on this?

**Comment by TrumanRu** [comment]
It's still the big problem to use vue-select in our project. So sad...

**Comment by tonykaralis** [comment]
Its a massive problem still. We use this a lot and after hacking tons of CSS it still doesn't work properly.

This should be a priority fix as it breaks the UI, apart from that the component is spot on.

**Comment by jeff-wood-readyup** [comment]
Also having this problem with a timezone field.

**Comment by abellong** [comment]
> Moreover all our examples break vue-select in multiple mode.
> 
> ![image](https://user-images.githubusercontent.com/15179453/86890571-2dc3e980-c106-11ea-881b-4eaf5fc409f0.png)
> 
> It would be amazing if @sagalbot would somehow recommend how to perfectly resolve this.

Most of the time we can easily figure out what the ellipsis stands for in single mode. But it's recommeded not to omit overflowed options in multiple mode. It's better to leave the multiple mode alone: narrow the css selector to '.vs--single .vs__selected-options' and '.vs--single .vs__selected-options'.

**Comment by ChefAndy** [comment]
I haven't done much testing, I'm admittedly not a CSS _guru_ per se, and this solution is a bit hackish, but I think it's going to do the trick in my scenario:

```
.v-select:not(.vs--open) .vs__dropdown-toggle .vs__selected-options .vs__selected + input {
  position: absolute;
}
```
The + is the sibling selector and .vs__selected only exists when something is selected and excluding .vs--open will display it whenever the dropdown is open. The regular placeholder and everything show up when nothing is selected, you can type in the field normally when something is selected, and the input element still exists and is part of the regular tab order... but it won't affect the geometry of the element.

<img width="330" alt="Screen Shot 2021-06-08 at 1 52 08 PM" src="https://user-images.githubusercontent.com/1882536/121233707-e5a2cf00-c860-11eb-95a7-20a322200d8b.png">

Not the most beautiful thing in the world, but many of the long names we deal with would be similar or exactly the same with only the first few characters revealed.

If someone sees a big caveat to this approach that I'm missing, I'd be happy to hear it. Maybe there's another element under .vs__selected-options in some situations that could make the input and .vs__selected element no longer direct siblings, or something?

**Comment by yoongti** [comment]
The solution that works for me is this (For single select)

```
.v-select {
    &:not(.vs--open) {
      .vs__selected + .vs__search {
        height: 0;
        margin: 0;
      }
    }

    .vs__selected-options {
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
  }
```

**Comment by consciousnessdev** [comment]
> The solution that works for me is this (For single select)
> 
> ```
> .v-select {
>     &:not(.vs--open) {
>       .vs__selected + .vs__search {
>         height: 0;
>         margin: 0;
>       }
>     }
> 
>     .vs__selected-options {
>       overflow: hidden;
>       text-overflow: ellipsis;
>       white-space: nowrap;
>     }
>   }
> ```

This Works For Single Option Thanks @yoongti :D

**Comment by edcoreweb** [comment]
Solution which worked for me, for single select, inspired by @yoongti 

```scss
.vs--single {
  &:not(.vs--open) .vs__selected + .vs__search {
    // force this to not use any space
    // we still need it to be rendered for the focus
    width: 0;
    padding: 0;
    margin: 0;
    border: none;
    height: 0;
  }

  .vs__selected-options {
    // do not allow growing
    width: 0;
  }

  .vs__selected {
    display: block;
    white-space: nowrap;
    text-overflow: ellipsis;
    max-width: 100%;
    overflow: hidden;
  }
}
```

![image](https://user-images.githubusercontent.com/9083523/134222522-39876048-5604-4d77-b221-92dc74448625.png)
