### ISSUE TITLE
How to change clear button just like deselect and OpenIndicator component

### ISSUE THREAD

**Issue by jsinhSolanki** [sagalbot/vue-select#886]
**Describe the bug**
I changed Deselect & OpenIndicator components according to my theme. But recently I found that there are two clear buttons. I got success in changing one through this guide but I can not change second close which appears when we have type for searching option. Check below image.

**To Reproduce**
You can check this in here. Just type something and cross icon popups(which is blue & I cant change it with Deselect component).

**Expected behavior**
This blue close/clear button should also get same UI/Component as we do with Deselect component.

**Screenshots**
Component which I want to change:
![blue-btn](https://user-images.githubusercontent.com/31243533/58785713-adc67880-8603-11e9-99cf-4d9bee2bb515.png)

Updated deselect component and above one should look same:
![over](https://user-images.githubusercontent.com/31243533/58785736-bcad2b00-8603-11e9-9a4b-297391681443.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2
 - Browser: Chrome
 - Version: 3.1.0

**Comment by francoism90** [comment]
Same question here, how is this controlled? I cannot find the style/JS responsible for it.

@jsinhSolanki I assume you didn't solve this.

**Comment by francoism90** [comment]
@jsinhSolanki https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

This seems to be a bit hardcoded, although it should be possible to overrule the button.

**Comment by sagalbot** [comment]
Really weird actually. Since `3.0` there have been styles to disable the browser default clear button:

```css
.vs__search::-webkit-search-decoration,
.vs__search::-webkit-search-cancel-button,
.vs__search::-webkit-search-results-button,
.vs__search::-webkit-search-results-decoration,
.vs__search::-ms-clear {
  display: none;
}
```

However, it seems that when the declaration is grouped like that, it gets ignored. Not sure why this happens, maybe it's a PostCSS/Autoprefixer thing. #984 solves it by giving it's own declaration.
