### ISSUE TITLE
Delete default animation 

### ISSUE THREAD

**Issue by NicaBihovetz** [sagalbot/vue-select#955]
I need to remove the completely default animation from vue-select. How to do it? I tried to replace the styles from the box with my own, but I didn’t get the result..

**Comment by sagalbot** [comment]
1. `transition` prop. This prop sets the name of the `<transition>` that wraps the dropdown. You could change it to an empty string.

```html
<v-select transition="" />
```

2. CSS. Override the default `vs__fade` transition duration.

```css
  .vs__fade-enter-active,
  .vs__fade-leave-active {
    transition: none;
  }
```
