### ISSUE TITLE
Inline support (CSS)

### ISSUE THREAD

**Issue by damms005** [sagalbot/vue-select#967]
Currently, the rendered layout look like a `block` level <div>

It will be much helpful if `<v-select>` can fit inline, i.e. `<v-select style'display:inline'>...`

Thanks

**Comment by sagalbot** [comment]
![image](https://user-images.githubusercontent.com/692538/67581442-deb36100-f6fc-11e9-840d-a9efbce5fd3c.png)

---

Doable with a bit of CSS.

```css
.v-select {
  display: inline-block;
  width: auto; 
  min-width: 11em;
}
```
